name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # in the future we'll add an arm image for the raspberry
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set variables
        run: |
            VER=$( grep -E '^version' build.gradle.kts | cut -d '"' -f 2 )
            echo "CURRENT_VERSION=$VER" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            livingwithhippos/unchainedbotkotlin:latest
            livingwithhippos/unchainedbotkotlin:${{ env.CURRENT_VERSION }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
